name: Node continues  intigration

on:
  pull_request:
    branchs: [master]

jobs:
  test_pull_request: 
      runs_on: ubantu_letest,
      steps: 
        uses: actions/checkout@v2
        uses: actions/setup_node@v1
        with:
          node_version: 12
        run: npm ci
        run: npm test
        run: npm run build 